
server:
    port: 8080

spring:
    jpa:
        properties:
            hibernate:
                default_schema: public
                dialect: org.hibernate.dialect.PostgreSQLDialect
                naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        hibernate:
            ddl_auto: validate

spring:
    profiles:
        active: postgres
    datasource:
        url: jdbc:postgresql://localhost:5432/bx
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    flyway:
        locations: classpath:db/migration/postgres
        schemas: public