
server:
    port: 8080

spring:
    jpa:
        hibernate:
            ddl_auto: none
            default_schema: bx
            dialect: org.hibernate.dialect.MySQLDialect
            naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy


naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy


spring:
    profiles:
        active: mysql
    datasource:
        url: jdbc:mysql://localhost:3306/bx?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver


flyway:
    locations: classpath:db/migration/mysql
    schemas: bx