server:
    port: 8080

spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: sa

spring:
    jpa:
        properties:
            hibernate:
                dataSourceClassName: org.h2.Driver
                default_schema: bx
                dialect: org.hibernate.dialect.MySQLDialect
                naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        hibernate:
            ddl_auto: create

