server:
    port: 8080

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: org.h2.Driver
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: sa


spring:
    jpa:
        hibernate:
            ddl_auto: create
            default_schema: bx
            naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy


naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
