version: '2'
services:
    bx-spring-oracle:
        image: bx-spring
        environment:
            SPRING_PROFILES_ACTIVE: oracle
            SPRING_DATASOURCE_URL: jdbc:oracle:thin:@bx-db-oracle:1521/xe
            SLEEP_START: 60
        ports:
            - 8080:8080
    bx-db-oracle:
        image: sath89/oracle-xe-11g
        environment:
            DEFAULT_SYS_PASS: oracle
            NLS_LANG: AMERICAN_CIS.UTF8
        ports:
            - 1521:1521